version: '3.7'

services:
  ml:
    container_name: ml
    build:
      context: .
      dockerfile: Dockerfile

    volumes:
      - ../:/workspace
      - /var/run/docker.sock:/var/run/docker.sock
      - ~/.ssh:/root/.ssh:ro
      - ~/.gitconfig:/root/.gitconfig:ro
      - ~/Documents/Pems/:/root/Documents/Pems/:ro
    command: sleep infinity

    # Uncomment the next four lines if you will use a ptrace-based debugger like C++, Go, and Rust.
    cap_add:
      - SYS_PTRACE
    security_opt:
      - seccomp:unconfined
    networks:
      - ml
networks:
  ml:
#    external: true
